### ISSUE TITLE
Profile picture appears rotated 90 degree (horizontal) when displayed as avatar

### ISSUE THREAD

**Issue by andylitalo** [surp-hovhannes/bahk#24]
![Live and Pray](https://github.com/surp-hovhannes/bahk/assets/13158190/702be536-7179-431d-83e7-30aa4ddb572d)

First avatar thumbnail is horizontal, but appears vertical in "Profile" section.

**Comment by andylitalo** [comment]
Fixed the bug! I'll make a PR and merge

**Comment by andylitalo** [comment]
I can't seem to reproduce the bug on my local instance on my laptop. Could this be a bug on mobile only? I'll look into testing on mobile first.

**Comment by mattash** [comment]
It's typically caused by mishandling EXIF data of photos from smartphone cameras. I just deployed the recent merge. Try to re-upload the image your previously used on the live version.

**Comment by andylitalo** [comment]
Did you deploy to the public site on heroku? I still see the bug on mobile.

I was able to access my local server on mobile and reproduce the error--your branch fixed it!

**Comment by mattash** [comment]
Oops, I thought it has been merged with main already. I just reviewed and merge the PR, so it should deploy to the public site shortly.
